version: '3.8'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - .:/opt/app
    working_dir: /opt/app